#include "drawing/Drawing.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <sstream>

#include <glm/common.hpp>

namespace {

struct Aabb {
  glm::vec3 min{0.0f};
  glm::vec3 max{0.0f};
  bool valid = false;
};

Aabb meshAabb(const StlMesh& mesh) {
  Aabb box;
  const auto& verts = mesh.vertices();
  if (verts.empty()) return box;
  box.min = verts.front().position;
  box.max = verts.front().position;
  box.valid = true;
  for (const auto& v : verts) {
    box.min = glm::min(box.min, v.position);
    box.max = glm::max(box.max, v.position);
  }
  return box;
}

DrawingView makeRectView(DrawingViewKind kind, const std::string& label,
                         float width, float height) {
  DrawingView view;
  view.kind = kind;
  view.label = label;
  view.widthMm = std::max(width, 0.0f);
  view.heightMm = std::max(height, 0.0f);
  view.outline = {
      {0.0f, 0.0f},
      {view.widthMm, 0.0f},
      {view.widthMm, view.heightMm},
      {0.0f, view.heightMm},
      {0.0f, 0.0f},
  };
  return view;
}

std::string pdfEscape(const std::string& s) {
  std::string out;
  out.reserve(s.size());
  for (char c : s) {
    if (c == '(' || c == ')' || c == '\\') out.push_back('\\');
    out.push_back(c);
  }
  return out;
}

}  // namespace

bool buildDrawingSheet(const StlMesh& mesh, const std::string& objectName,
                       float sectionRatio, DrawingSheet& out, std::string& error) {
  const Aabb box = meshAabb(mesh);
  if (!box.valid) {
    error = "Selected object has no mesh data";
    return false;
  }

  const float widthX = box.max.x - box.min.x;
  const float widthY = box.max.y - box.min.y;
  const float widthZ = box.max.z - box.min.z;
  if (widthX <= 0.0f || widthY <= 0.0f || widthZ <= 0.0f) {
    error = "Selected object has invalid bounds";
    return false;
  }

  sectionRatio = std::clamp(sectionRatio, 0.0f, 1.0f);
  out = {};
  out.title = objectName.empty() ? "Drawing" : (objectName + " Drawing");
  out.sectionRatio = sectionRatio;
  out.views.push_back(makeRectView(DrawingViewKind::Front, "Front", widthX, widthZ));
  out.views.push_back(makeRectView(DrawingViewKind::Top, "Top", widthX, widthY));
  out.views.push_back(makeRectView(DrawingViewKind::Right, "Right", widthY, widthZ));

  const float sectionX = widthX * sectionRatio;
  out.views.push_back(makeRectView(DrawingViewKind::Section, "Section A-A", sectionX, widthZ));

  out.dimensions.push_back({"Width", widthX});
  out.dimensions.push_back({"Depth", widthY});
  out.dimensions.push_back({"Height", widthZ});
  out.dimensions.push_back({"Section X", sectionX});
  return true;
}

bool exportDrawingDxf(const std::string& path, const DrawingSheet& sheet,
                      std::string& error) {
  std::ofstream out(path);
  if (!out) {
    error = "Failed to open DXF output path";
    return false;
  }

  out << "0\nSECTION\n2\nHEADER\n0\nENDSEC\n";
  out << "0\nSECTION\n2\nENTITIES\n";

  float xOrigin = 0.0f;
  const float yOrigin = 0.0f;
  for (const auto& view : sheet.views) {
    for (size_t i = 1; i < view.outline.size(); ++i) {
      const glm::vec2 a = view.outline[i - 1] + glm::vec2(xOrigin, yOrigin);
      const glm::vec2 b = view.outline[i] + glm::vec2(xOrigin, yOrigin);
      out << "0\nLINE\n8\nCAMSTER_DRAWING\n";
      out << "10\n" << a.x << "\n20\n" << a.y << "\n30\n0.0\n";
      out << "11\n" << b.x << "\n21\n" << b.y << "\n31\n0.0\n";
    }

    out << "0\nTEXT\n8\nCAMSTER_DRAWING\n";
    out << "10\n" << xOrigin << "\n20\n" << (yOrigin - 6.0f) << "\n30\n0.0\n";
    out << "40\n4.0\n1\n" << view.label << "\n";

    xOrigin += view.widthMm + 30.0f;
  }

  out << "0\nTEXT\n8\nCAMSTER_DRAWING\n10\n0.0\n20\n-20.0\n30\n0.0\n40\n5.0\n1\n"
      << sheet.title << "\n";

  float dimY = -32.0f;
  for (const auto& dim : sheet.dimensions) {
    out << "0\nTEXT\n8\nCAMSTER_DIM\n10\n0.0\n20\n" << dimY
        << "\n30\n0.0\n40\n3.5\n1\n"
        << dim.label << ": " << std::fixed << std::setprecision(3) << dim.valueMm << " mm\n";
    dimY -= 6.0f;
  }

  out << "0\nENDSEC\n0\nEOF\n";
  return true;
}

bool exportDrawingPdf(const std::string& path, const DrawingSheet& sheet,
                      std::string& error) {
  std::ostringstream content;
  content << "BT\n/F1 18 Tf\n72 770 Td\n(" << pdfEscape(sheet.title) << ") Tj\nET\n";
  content << "BT\n/F1 11 Tf\n72 748 Td\n(Generated by camster drawing baseline) Tj\nET\n";

  float y = 724.0f;
  for (const auto& dim : sheet.dimensions) {
    content << "BT\n/F1 11 Tf\n72 " << y << " Td\n(" << pdfEscape(dim.label)
            << ": " << std::fixed << std::setprecision(3) << dim.valueMm << " mm) Tj\nET\n";
    y -= 16.0f;
  }

  std::ostringstream pdf;
  std::vector<long> offsets;
  offsets.reserve(6);
  pdf << "%PDF-1.4\n";

  offsets.push_back(static_cast<long>(pdf.tellp()));
  pdf << "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n";

  offsets.push_back(static_cast<long>(pdf.tellp()));
  pdf << "2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj\n";

  offsets.push_back(static_cast<long>(pdf.tellp()));
  pdf << "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
         "/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n";

  offsets.push_back(static_cast<long>(pdf.tellp()));
  pdf << "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n";

  const std::string contentStr = content.str();
  offsets.push_back(static_cast<long>(pdf.tellp()));
  pdf << "5 0 obj\n<< /Length " << contentStr.size() << " >>\nstream\n"
      << contentStr << "endstream\nendobj\n";

  const long xrefPos = static_cast<long>(pdf.tellp());
  pdf << "xref\n0 6\n";
  pdf << "0000000000 65535 f \n";
  for (long off : offsets) {
    pdf << std::setw(10) << std::setfill('0') << off << " 00000 n \n";
  }
  pdf << "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n";
  pdf << xrefPos << "\n%%EOF\n";

  std::ofstream out(path, std::ios::binary);
  if (!out) {
    error = "Failed to open PDF output path";
    return false;
  }
  out << pdf.str();
  return true;
}
